Upgrade to v3.16.0 of the Cloudflare Terraform Provider
pulumi/pulumi-cloudflare pull request #263
Opened 2022-06-13 15:32 UTC by stack72

Fixes: #256
Fixes: #262
Fixes: #265
Fixes: #264
Fixes: #267

2022-06-27 11:20 UTC, stack72 commented
this will be merged today with v3.17.0 support as well

2022-06-27 21:06 UTC, jkodroff requested changes

2022-06-27 21:06 UTC, jkodroff commented on provider/resources.go
> +				Tok: tfbridge.MakeResource(mainPkg, mainMod, "LogPushOwnershipChallenge"),
`LogpushOwnershipChallenge`

2022-06-29 17:37 UTC, jkodroff approved these changes

2022-06-29 17:42 UTC, merged